updated github action scripts
Signed-off-by: Disaiah Bennett <dbennett@redhat.com>

diff --git a/.github/workflows/regenerate-bundles-2.7.yml b/.github/workflows/regenerate-bundles-2.7.yml
--- a/.github/workflows/regenerate-bundles-2.7.yml
+++ b/.github/workflows/regenerate-bundles-2.7.yml
@@ -35,32 +35,25 @@ jobs:
     
       # Runs a set of commands using the runners shell
       - name: Regenerate Operator Bundles
-        continue-on-error: true
         id: generate_bundle
         run: |
           make regenerate-operator-bundles
-
-      - name: Check Job Status
-        id: job_status
-        run: |
-          if [[ ${{ steps.generate_bundle.outcome }} == 'failure' ]]; then
-            echo "status=failure" >> $GITHUB_OUTPUT
-          else
-            echo "status=success" >> $GITHUB_OUTPUT
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Regenerate Operator Bundles step failed with exit code $exit_code"
+            exit $exit_code
           fi
 
       - name: Send Slack Message on Failure
-        if: steps.job_status.outputs.status == 'failure'
+        if: ${{ failure() }}
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         run: |
-          # Compose the Slack message
           SLACK_MESSAGE=":exclamation: *GitHub Actions Job Failed* :exclamation:\n\n"
           SLACK_MESSAGE+="Job Name: $GITHUB_WORKFLOW/$GITHUB_JOB\n"
           SLACK_MESSAGE+="Job URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\n"
           SLACK_MESSAGE+="Error Details: Your job failed. Please check the job logs for more information."
 
-          # Send the message to Slack
           curl -X POST -H "Content-type: application/json" --data "{
             \"text\": \"$SLACK_MESSAGE\"
           }" $SLACK_WEBHOOK_URL
