updated Github Actions to include workflow overrides
Signed-off-by: dislbenn <dbennett@redhat.com>

diff --git a/.github/workflows/regenerate-bundles.yml b/.github/workflows/regenerate-bundles.yml
--- a/.github/workflows/regenerate-bundles.yml
+++ b/.github/workflows/regenerate-bundles.yml
@@ -10,6 +10,17 @@ on:
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+    inputs:
+      branch_arg:
+        description: 'BRANCH agrument for the make command'
+        required: false
+        default: 'main'
+        type: string
+      org_arg:
+        description: 'ORG argument for the make command'
+        required: false
+        default: 'stolostron'
+        type: string
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -55,7 +66,12 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Regenerate Operator Charts From Bundles
         run: |
-          make regenerate-charts-from-bundles
+          make regenerate-charts-from-bundles BRANCH=${{ github.event.inputs.branch_arg }} ORG=${{ github.event.inputs.org_arg }}
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Regenerate Operator Charts From Bundles step failed with exit code $exit_code"
+            exit $exit_code
+          fi
 
       - name: Generate code
         run: |
